apiVersion: v1
kind: Secret
metadata:
  name: fc-postgres-pass-secret-part
  namespace: federated-catalogue-partner
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: postgres
