apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: federated-catalogue-partner
  name: fc-postgres-volume-part
  labels:
    app: fc-service-part
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/shared-data/postgresql-part
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: federated-catalogue-partner
  name: fc-postgres-claim-part
  labels:
    app: fc-service-part
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi