include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml  
  - template: Security/SAST.gitlab-ci.yml
  - project: eclipse/xfsc/dev-ops/ci-templates
    file: maven-standard-ci.yaml
    ref: main
    
variables:
  MAVEN_IMAGE: "maven:3.9-eclipse-temurin-17"
      
stages:
  - test
  - build
  - deploy
  
maven:test:
  script:
    - mvn $MAVEN_CLI_OPTS verify
    - cat service/target/site/jacoco/index.html | grep -o '<tfoot>.*</tfoot>'
  artifacts:
    paths:
      - 'service/target/site/jacoco/index.html'
#      - '**/target/*-src.zip'
#      - '**/pom.xml'
#      - 'clients/java/target/*.jar'
#    exclude:
#      - clients/java/target/*-full.jar  

# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
sast:
  stage: build
