management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  profiles:
    active: ${APPLICATION_PROFILES:default}
  application:
    name: ${APPLICATION_NAME:federated-catalogue-service-app}
  mvc:
    log-request-details: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://key-server:8080/realms/gaia-x
#          jwk-set-uri: http://key-server:8080/realms/gaia-x/protocol/openid-connect/certs
  liquibase:
    change-log: classpath:/liquibase/master-changelog.xml

openapi:
  gaiaXCatalogue:
    base-path: ""

springdoc:
  api-docs:
    path: /api/docs
    enabled: true

keycloak:
  auth-server-url: http://key-server:8080
  realm: gaia-x
  resource: federated-catalogue
  credentials:
    secret: vZo1equicRl1UdxJDWCNNJWe6vJcm2Cg

datastore:
  database-driver: org.h2.Driver
  database-url: jdbc:h2:mem:testdb;SCHEMA=PUBLIC;DB_CLOSE_DELAY=-1
  database-username: example
  database-password: example
  file-path: target
#  database-driver: org.postgresql.Driver
#  database-url: jdbc:postgresql://localhost:5432/catalog
#  database-username: gaiax
#  database-password: gaiax

logging:
  level:
    root: INFO
    eu.gaiax.difs.fc: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.keycloak.adapters.OAuthRequestAuthenticator: DEBUG
