management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  profiles:
    active: ${APPLICATION_PROFILES:default}
  application:
    name: ${APPLICATION_NAME:federated-catalogue-service-app}
  mvc:
    log-request-details: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gaia-x
          jwk-set-uri: http://localhost:8080/realms/gaia-x/protocol/openid-connect/certs

openapi:
  gaiaXCatalogue:
    base-path: ""

springdoc:
  api-docs:
    path: /api/docs
    enabled: true

federated-catalogue:
  security:
    resource-id: federated-catalogue

keycloak:
  auth-server-url: http://localhost:8080
#  auth-server-url: http://key-server.gxfs.dev
  realm: gaia-x
#  resource: federated-catalogue
  resource: admin-cli
  credentials:
#    secret: fwirOT4r8s3DC45CHtUNUNthfnogLAal
    secret: 5OlXNJpIk2nFfj6lTffBBUexsHyM8AUm
#    secret: wuk19sLN8EyiTxOcuLpXUt1o19SXBaJq

logging:
  level:
    root: INFO
    eu.gaiax.difs.fc.server: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.keycloak.adapters.OAuthRequestAuthenticator: DEBUG