version: '3.7'

services:
  keycloak:
    container_name: "federated-catalogue-keycloak"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      PROXY_ADDRESS_FORWARDING: "true"
    image: "quay.io/keycloak/keycloak:17.0.1"
    ports:
      - "8080:8080"
    networks:
      - "gaia-x"
    restart: unless-stopped
    extra_hosts:
      - "auth-server:127.0.0.1"
    volumes:
      - "../keycloak/providers:/opt/keycloak/providers"
      - "../keycloak/realms:/tmp/import"
    command:
      [
          'start-dev --auto-build',
          '-Dkeycloak.migration.action=import',
          '-Dkeycloak.migration.provider=dir',
          '-Dkeycloak.migration.dir=/tmp/import',
          '-Dkeycloak.migration.strategy=OVERWRITE_EXISTING',
          '-Dkeycloak.profile.feature.upload_scripts=enabled',
          '--log-level=DEBUG,io.quarkus:INFO,liquibase:INFO,org.hibernate:INFO,org.infinispan:INFO,org.keycloak.services.scheduled:INFO,org.keycloak.transaction:INFO,io.netty.buffer.PoolThreadCache:INFO,org.keycloak.models.sessions.infinispan:INFO'
      ]
  server:
    container_name: "federated-catalogue-server"
    image: "${CI_REGISTRY}/fc-service-server:0.0.1-SNAPSHOT"
    ports:
      - "8081:8081"
    networks:
      - "gaia-x"
    restart: unless-stopped

  portal:
    container_name: "federated-catalogue-portal"
    image: "${CI_REGISTRY}/fc-demo-portal:0.0.1-SNAPSHOT"
    ports:
      - "8088:8088"
    networks:
      - "gaia-x"
    restart: unless-stopped

networks:
  gaia-x:
    driver: "bridge"